language: python
python:
  - "3.2"
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests, e.g. python setup.py test
# --source specifies what packages to cover, you probably want to use that option
script:
  coverage run --source=app src/manage.py test app
after_success:
  coveralls
